defaultRules:
  create: true

kubeEtcd:
  enabled: false
kubeControllerManager:
  enabled: false
kubeScheduler:
  enabled: false

prometheusOperator:
  resources:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      cpu: 200m
      memory: 200Mi

prometheus:
  service:
    type: ClusterIP
  prometheusSpec:
    replicas: 1
    retention: 2d
    retentionSize: 3GB
    serviceMonitorSelectorNilUsesHelmValues: false
    ruleSelectorNilUsesHelmValues: false
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        cpu: 750m
        memory: 900Mi

alertmanager:
  service:
    type: ClusterIP
  alertmanagerSpec:
    replicas: 1
    retention: 24h
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 150m
        memory: 160Mi

grafana:
  replicas: 1
  service:
    type: ClusterIP
  ingress:
    enabled: false
  defaultDashboardsEnabled: false
  sidecar:
    dashboards:
      enabled: true
      searchNamespace: ALL
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
  resources:
    requests:
      cpu: 75m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 300Mi

kube-state-metrics:
  replicas: 1
  resources:
    requests:
      cpu: 25m
      memory: 48Mi
    limits:
      cpu: 100m
      memory: 128Mi

prometheus-node-exporter:
  resources:
    requests:
      cpu: 25m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
