apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: game-session-api
  namespace: monitoring
  labels:
    app.kubernetes.io/part-of: gameops-platform-lab
spec:
  namespaceSelector:
    matchNames:
      - gameops
  selector:
    matchLabels:
      app.kubernetes.io/name: game-session-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
